### PR TITLE
Upgrade to Polymer 2.0 and refactor

### PR DESCRIPTION
**Pull request by arjunyel**
This pull request has two breaking changes:

1. Element has been upgraded to use the ES6 Polymer 2.0 syntax.

2. CSS Custom Property names have been refactored and a property for z-index has been added. I updated the default colors to Github's theme and took out the -default variables for better performance.

### CODE REVIEW

**Comment by arjunyel** [comment]
@afonsopacifer what do you think, any chance of merging this?

**Comment by afonsopacifer** [comment]
Wow, sorry for delay! Thanks :) Great job <3

**Comment by arjunyel** [comment]
Thanks for the great element! When you get a chance please update bower and webcomponents.org 😄

**Comment by arjunyel** [comment]
@afonsopacifer Any chance of updating this on bower?

**Pull request merged**
